#pragma once
#include "TestRegisters.h"



#define TEST_FUNCTION_IN_SUITE_CASE_DECLARE(FUNC_NAME, SUITE) \
void FUNC_NAME();\
static ::darknessNight_CppUnitTestFramework::TestFuncRegister FUNC_NAME##Register(FUNC_NAME,#FUNC_NAME, SUITE, __FILE__, __LINE__);


#define TEST_FUNCTION_IN_SUITE_CASE(FUNC_NAME, SUITE) \
TEST_FUNCTION_IN_SUITE_CASE_DECLARE(FUNC_NAME, SUITE) \
void FUNC_NAME()


#define TEST_FUNCTION(FUNC_NAME) TEST_FUNCTION_IN_SUITE_CASE(FUNC_NAME,"")

#define TEST_FUNCTION_DECLARE(FUNC_NAME) TEST_FUNCTION_IN_SUITE_CASE_DECLARE(FUNC_NAME,"")


#define IGNORE_TEST_CLASS(CLASS_NAME, IGNORE_CAUSE)\
class CLASS_NAME


#define IGNORE_TEST_FUNCTION_IN_SUITE_CASE(FUNC_NAME, SUITE, IGNORE_CAUSE) \
void FUNC_NAME()


#define IGNORE_TEST_FUNCTION(FUNC_NAME, IGNORE_CAUSE) TEST_FUNCTION_IN_SUITE_CASE(FUNC_NAME,"", IGNORE_CAUSE)